# Qdrant configuration for JEEX Plan
# Optimized for multi-tenancy and document embeddings

service:
  http_port: 6333
  grpc_port: 6334
  enable_cors: true
  max_request_size_mb: 32
  max_workers: 0  # Auto-detect CPU cores
  enable_tls: false  # Enable for production
  tls_cert: ./certs/cert.pem
  tls_key: ./certs/key.pem
  timeout_sec: 30
  write_concern: 1  # Faster writes for MVP
  read_fallback: true

log_level: info

# Performance optimizations for multi-tenancy
storage:
  storage_path: /qdrant/storage
  snapshots_path: /qdrant/snapshots
  # Use SSD-optimized settings
  wal_capacity_mb: 32
  wal_segments_ahead: 2
  # Optimize for document embeddings (~1536 dimensions)
  vectors:
    # 1536 dimensions for OpenAI embeddings
    size: 1536
    distance: Cosine

# Cluster configuration (single node for MVP)
cluster:
  enabled: false

# Collection configuration defaults
collections:
  # Multi-tenancy optimized HNSW parameters
  hnsw_config:
    m: 0  # Disable global graph for multi-tenancy
    payload_m: 16  # Create payload-specific connections
    ef_construct: 100
    full_scan_threshold: 10000

  # Optimized for payload filtering
  payload_indexing:
    enabled: true
    # Index tenant and project IDs for fast filtering
    indexed_fields:
      - tenant_id
      - project_id
      - type
      - visibility