# Qdrant configuration for JEEX Plan
# Optimized for multi-tenancy and document embeddings (v1.15.4)

service:
    http_port: 6333
    grpc_port: 6334
    enable_cors: true
    max_request_size_mb: 32
    max_workers: 0 # Auto-detect CPU cores
    enable_tls: false # Enable for production
    tls_cert: ./certs/cert.pem
    tls_key: ./certs/key.pem
    timeout_sec: 30
    write_concern: 1 # Faster writes for MVP
    read_fallback: true

log_level: info

# Performance optimizations for multi-tenancy
storage:
    storage_path: /qdrant/storage
    snapshots_path: /qdrant/snapshots

    # WAL configuration
    wal:
        wal_capacity_mb: 32
        wal_segments_ahead: 2

# Cluster configuration (single node for MVP)
cluster:
    enabled: false
# Default collection parameters (used when creating collections)
# Vector configuration is set per collection, not globally
# HNSW and payload indexes are configured per collection
